"""
V10.4: Python Code Generator
============================

Transpiles visual workflow nodes into standalone, executable Python scripts.
Supports:
- Smart dependency detection
- Robust error handling
- Type-safe code generation

Usage:
    generator = CodeGenerator()
    script = generator.generate(nodes)
"""

import datetime
import json
from typing import List, Dict, Any, Set
from core.models import WorkflowNode


class CodeGenerator:
    def __init__(self):
        self.imports: Set[str] = set()
        self.helpers: Set[str] = set()
        
    def generate(self, nodes: List[WorkflowNode]) -> str:
        """Generate full Python script from workflow nodes"""
        self.imports = {"import time", "import logging", "from adbutils import adb"}
        self.helpers = set()
        
        main_body = []
        indent = "    "
        
        # 1. Generate Main Body
        for i, node in enumerate(nodes):
            code_block = self._transpile_node(node)
            if code_block:
                main_body.append(f"{indent}# --- Step {i+1}: {node.action_type} ---")
                # Add logging
                msg = f"Step {i+1}: {node.step_name}" if hasattr(node, 'step_name') else f"Step {i+1}"
                main_body.append(f'{indent}print("👉 {msg}")')
                
                # Indent logic handling (basic)
                for line in code_block.split('\n'):
                    if line.strip():
                        main_body.append(f"{indent}{line}")
                main_body.append("") # Empty line
        
        # 2. Assemble Script
        header = self._generate_header()
        helpers = self._generate_helpers()
        
        # 3. Add Boilerplate
        script = [
            header,
            "\n".join(sorted(list(self.imports))),
            "",
            "# === Runtime Helpers ===",
            helpers,
            "",
            "def main():",
            f'{indent}logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")',
            f'{indent}print("🚀 Starting Automation Script...")',
            "",
            f'{indent}# Connect to device',
            f'{indent}try:',
            f'{indent}    device = adb.device()',
            f'{indent}    print(f"📱 Connected to {{device.serial}}")',
            f'{indent}except Exception as e:',
            f'{indent}    print(f"❌ Device connection failed: {{e}}")',
            f'{indent}    return',
            "",
            "\n".join(main_body),
            f'{indent}print("✅ Workflow Completed Successfully!")',
            "",
            'if __name__ == "__main__":',
            f'{indent}main()'
        ]
        
        return "\n".join(script)

    def _generate_header(self) -> str:
        return f'''# -*- coding: utf-8 -*-
"""
Generated by Antigravity Automation
Timestamp: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
'''

    def _generate_helpers(self) -> str:
        helper_code = []
        
        if "check_text" in self.helpers:
            self.imports.add("import cv2")
            self.imports.add("import numpy as np")
            # Minimal OCR/Template helper would go here
            # For standalone scripts, we might need to assume RapidOCR is installed or simplify
            pass
            
        return "\n".join(helper_code)

    def _transpile_node(self, node: WorkflowNode) -> str:
        """Convert single node to Python code block"""
        action = node.action_type
        params = str(node.params)
        
        # --- Interaction ---
        if action == "Click Region":
            # Extract coords
            x = (node.coords.get('x1', 0) + node.coords.get('x2', 0)) / 2
            y = (node.coords.get('y1', 0) + node.coords.get('y2', 0)) / 2
            # Use percent to pixel? Assume device var available
            # Ideally generated script should handle resolution. 
            # For now, let's output absolute coordinates comment or generic click
            return f"device.click({int(x * 1080)}, {int(y * 2400)})  # TODO: Handle resolution dynamically"
            
        elif action == "Swipe":
             return "device.swipe(500, 1500, 500, 500, 0.5) # Default swipe up"
             
        elif action == "Input Text (Base64)":
            # Simplified for standalone
            import base64
            # We assume input content is in params
            text = params
            if "${" in text:
                return f'# Variable input not fully supported in standalone yet: {text}'
            b64 = base64.b64encode(text.encode('utf-8')).decode('utf-8')
            return f'device.shell("ime set com.android.adbkeyboard/.AdbIME")\ndevice.shell(\'am broadcast -a ADB_INPUT_B64 --es msg "{b64}"\')'

        elif action == "Wait Time":
            seconds = params if params.isdigit() else "1"
            return f"time.sleep({seconds})"
            
        elif action == "HTTP Request":
            self.imports.add("import requests")
            try:
                p = json.loads(params)
                url = p.get('url', '')
                method = p.get('method', 'GET')
                return f'resp = requests.{method.lower()}("{url}")\nprint(f"🌐 HTTP Status: {{resp.status_code}}")'
            except:
                return f"# Invalid HTTP Params: {params}"
        
        # --- Logic ---
        elif action == "LOOP (Count)":
            count = params if params.isdigit() else "3"
            return f"for i in range({count}):"
            
        # Default fallback
        return f"# Action '{action}' logic generation pending..."

