
"""
V10.5: Python Script Generator (Control Flow Enabled)
=====================================================

Generates robust, standalone Python scripts from workflow steps.
Utilizes the core ActionLibrary to ensure execution parity with the GUI.

Features:
- Control Flow Support (IF/ELSE/LOOP) with proper indentation
- Reconstruction of StepData objects
- ParamSerializer integration for parameter restoration
- Automatic dependency and resource initialization
- HumanDevice integration with Cognitive Pauses

Usage:
    generator = ScriptGenerator()
    code = generator.generate(step_list)
"""

import datetime
from typing import List, Dict, Any, Optional

from core.node_definitions import get_node
from core.param_serializer import ParamSerializer


class ScriptGenerator:
    """
    Transpiles workflow steps into a Python script using core components.
    """
    
    def generate(self, steps: List[Dict[str, Any]]) -> str:
        """
        Generate Python script from a list of step dictionaries.
        
        Args:
            steps: List of dicts, each containing:
                   - action_type (str)
                   - step_name (str)
                   - params_form (Dict) OR params (str) [Internal params string]
                   - coords (Dict)
                   - context (str)
                   
        Returns:
            Full Python script string.
        """
        imports = [
            "import time",
            "import random", # Added for cognitive pause
            "import logging",
            "from pathlib import Path",
            "from adbutils import adb",
            "from rapidocr_onnxruntime import RapidOCR",
            "from core.action_library import ActionLibrary, StepData",
            "from core.variable_store import VariableStore",
            "from core.param_serializer import ParamSerializer",
            "from tools.human_device import HumanDevice"
        ]
        
        # Header
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        script = [
            "# -*- coding: utf-8 -*-",
            f'"""\nGenerated by Antigravity Low-Code\nTimestamp: {timestamp}\n"""',
            ""
        ]
        script.extend(imports)
        script.extend([
            "",
            "# === Setup Logging ===",
            "logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')",
            "logger = logging.getLogger(__name__)",
            "",
            "def main():",
            "    print('🚀 Starting Automation Script...')",
            "",
            "    # 1. Initialize Resources",
            "    try:",
            "        device = adb.device()",
            "        logger.info(f'📱 Connected to {device.serial}')",
            "    except Exception as e:",
            "        logger.error(f'❌ Failed to connect to device: {e}')",
            "        return",
            "",
            "    store = VariableStore()",
            "    ocr_engine = RapidOCR()",
            "    # Initialize Human Device for realistic interactions",
            "    human_device = HumanDevice(device)", 
            "", 
            "    logger.info('✅ Resources Initialized')",
            "",
            "    # 2. Workflow Execution"
        ])
        
        # Indentation State
        self.indent_level = 1 # Start inside main function
        self.script_lines = list(script) # Working copy
        
        # Body
        for i, step in enumerate(steps):
            action_type = step.get('action') or step.get('action_type')
            if not action_type:
                continue
                
            step_name = step.get('name') or step.get('step_name') or f"Step {i+1}"
            coords = step.get('coords', {})
            
            # --- Logic Loop Start ---
            
            # 1. Handle Control Flow Keywords
            if action_type.startswith("IF ("):
                # E.g., "IF (Check Text)"
                self._add_line(f"# --- {step_name} ---")
                
                # Check Logic
                method_name = self._get_method_name(action_type)
                
                # We need to construct the call arguments, similar to normal Action
                params_str = self._resolve_params(step, action_type)
                
                # Generate Condition Code
                # Example: if ActionLibrary.action_check_text(device, ...):
                
                call_args = ["device", "step_data", "store"]
                if self._is_vision_action(action_type):
                    call_args.append("ocr_engine=ocr_engine")
                # IF checks usually don't need human_device unless clicking, but 'Check' implies read-only
                
                # Construct StepData for the IF condition
                safe_params = params_str.replace("'", "\\'").replace('"', '\\"')
                
                self._add_line(f"logger.info('🤔 Logic Check: {step_name}')")
                self._add_line("step_data = StepData({")
                self._add_line(f"    'action_type': '{action_type}',")
                self._add_line(f'    "params": "{safe_params}",')
                self._add_line(f"    'coords': {coords}")
                self._add_line("})")
                
                self._add_line(f"if ActionLibrary.{method_name}({', '.join(call_args)}):")
                self.indent_level += 1
                continue
                
            elif action_type == "ELSE":
                self.indent_level -= 1
                self._add_line("else:")
                self.indent_level += 1
                continue
                
            elif action_type == "END IF":
                self.indent_level -= 1
                self._add_line("# End IF")
                continue
                
            elif action_type.startswith("LOOP"):
                # E.g. "LOOP LIST" or "LOOP COUNT" - This requires Python implementation
                # For simplicity, if we don't have loop param parsing fully implemented, 
                # we just generate a placeholder or infinite loop for now
                self._add_line(f"# --- {step_name} (Loop) ---")
                self._add_line("while True: # TODO: Replace with specific loop logic")
                self.indent_level += 1
                continue
                
            elif action_type == "END LOOP":
                self.indent_level -= 1
                self._add_line("# End LOOP")
                continue

            # --- Normal Action Generation ---
            
            internal_params = self._resolve_params(step, action_type)
            
            # Warning for Native Input with non-ASCII
            if action_type == "Input Text (Native)" and not internal_params.isascii():
                self._add_line(f"# WARNING: Native input may not support non-ASCII characters. Consider using Base64 input.")

            # Escape params for string literal
            safe_params = internal_params.replace("'", "\\'").replace('"', '\\"')
            
            # Construct Step Code
            self._add_line(f"# --- {step_name} ---")
            self._add_line(f"logger.info('👉 Executing: {step_name} ({action_type})')")
            
            method_name = self._get_method_name(action_type)
            
            if method_name:
                self._add_line("step_data = StepData({")
                self._add_line(f"    'action_type': '{action_type}',")
                self._add_line(f'    "params": "{safe_params}",') # Use double quotes for safety
                self._add_line(f"    'coords': {coords}")
                self._add_line("})")
                
                call_args = ["device", "step_data", "store"]
                
                if self._is_vision_action(action_type):
                    call_args.append("ocr_engine=ocr_engine")
                
                # Logic actions might take context (store is context)

                # Conditional HumanDevice injection
                if not self._is_readonly_vision_action(action_type):
                    call_args.append("human_device=human_device")
                
                self._add_line(f"ActionLibrary.{method_name}({', '.join(call_args)})")
                
                # Cognitive Pause (Anti-Detection) - Skip for explicit waits
                if action_type != "Wait Time":
                    self._add_line("# Cognitive Pause")
                    self._add_line("time.sleep(random.uniform(0.8, 1.8))")
                    
            else:
                self._add_line(f"# ⚠️ Unsupported Action: {action_type}")
            
            self._add_line("") # Spacer
            
        # Footer
        # Reset indent for footer
        self.indent_level = 1 
        self._add_line("logger.info('🎉 Workflow Execution Finished')")
        self._add_line("")
        
        self.indent_level = 0
        self._add_line("if __name__ == '__main__':")
        self.indent_level = 1
        self._add_line("main()")
        
        return "\n".join(self.script_lines)

    def _add_line(self, code: str):
        """Append line with current indentation"""
        indent = "    " * self.indent_level
        self.script_lines.append(f"{indent}{code}")

    def _resolve_params(self, step: Dict, action_type: str) -> str:
        """Resolve param string from form or raw"""
        if 'params_form' in step and isinstance(step['params_form'], dict):
            return ParamSerializer.to_internal(action_type, step['params_form'])
        elif 'params' in step:
            return str(step['params'])
        return ""

    def _get_method_name(self, action_type: str) -> Optional[str]:
        """Convert 'Check Text' to 'action_check_text' considering ACTION_MAPPING logic"""
        # Overrides for complex names
        if action_type == "Check Text": return "action_check_text"
        if action_type == "Input Text (Base64)": return "action_input_text_base64"
        if action_type == "Input Text (Native)": return "action_input_text_native"
        if action_type == "Click Region": return "action_click_region"
        if action_type == "Wait Time": return "action_wait_time"
        if action_type == "Load Excel Data": return "action_load_excel_data"
        if action_type == "Set Variable": return "action_set_variable"
        if action_type == "Print Variable": return "action_print_variable"
        
        # Logic Actions
        if action_type == "IF (Check Text)": return "action_check_text"
        if action_type == "IF (Check Image)": return "action_check_image"
        
        # Default fallback
        normalized = action_type.lower().replace(" ", "_").replace("&", "").replace("__", "_")
        return f"action_{normalized}"

    def _is_vision_action(self, action_type: str) -> bool:
        """Heuristic to determine if OCR engine is needed"""
        vision_actions = {
            "Check Text", "Wait Text", "Click Text", 
            "Wait Element", "Wait Until Disappear", "Assert Exists",
            "IF (Check Text)", "IF (Check Image)"
        }
        return action_type in vision_actions

    def _is_readonly_vision_action(self, action_type: str) -> bool:
        """
        Determine if action involves physical interaction.
        Returns True if it's purely visual/logic check (no touch).
        """
        readonly_set = {
            "Check Text", "Wait Text", "Assert Exists", 
            "Check Image", "Wait Element", "IF (Check Text)", "IF (Check Image)"
        }
        return action_type in readonly_set
